GET http://localhost:3000/

###
GET http://localhost:3000/items

###
GET http://localhost:3000/items/item
Content-Type: application/json

{
    "itemId": "615a8cb953925f3581eb6da6"
}

###
GET http://localhost:3000/img/pokemon-rojo.jpg

###
POST http://localhost:3000/items
Content-Type: application/json

{
    "title": "Sonic",
    "price": 6.99,
    "image": "sonic.jpg"
}

###

POST http://localhost:3000/create-payment-intent HTTP/1.1
Content-Type: application/json

[
    {
        "id": "615a8cad53925f3581eb6da4",
        "qty": 2
    }
]